#include "pch.h"
#include "system/reflection/ReflectionTools.h"
#include "core/reflection/GenMacros.h"

#include "asset/pods/GltfFilePod.h"
#include "asset/pods/ImagePod.h"
#include "asset/pods/MaterialPod.h"
#include "asset/pods/ModelPod.h"
#include "asset/pods/ShaderPod.h"
#include "asset/pods/StringPod.h"
#include "asset/pods/TexturePod.h"
#include "asset/pods/XMLDocPod.h"
