#include "pch.h"
#include "system/reflection/ReflectionTools.h"
#include "system/reflection/Reflector.h"

#include "asset/pods/CubemapPod.h"
#include "asset/pods/GltfFilePod.h"
#include "asset/pods/ImagePod.h"
#include "asset/pods/MaterialPod.h"
#include "asset/pods/ModelPod.h"
#include "asset/pods/ShaderPod.h"
#include "asset/pods/TextPod.h"
#include "asset/pods/TexturePod.h"
#include "asset/pods/XMLDocPod.h"
